.gitignore, build.gradle, src/main/java/com/dongsoop/dongsoop/config/SecurityConfig.java, src/main/java/com/dongsoop/dongsoop/exception/CustomException.java, src/main/java/com/dongsoop/dongsoop/exception/domain/jwt/TokenExpiredException.java, src/main/java/com/dongsoop/dongsoop/exception/domain/jwt/TokenMalformedException.java, src/main/java/com/dongsoop/dongsoop/exception/domain/jwt/TokenNotFoundException.java, src/main/java/com/dongsoop/dongsoop/exception/domain/jwt/TokenRoleNotAvailableException.java, src/main/java/com/dongsoop/dongsoop/exception/domain/jwt/TokenSignatureException.java, src/main/java/com/dongsoop/dongsoop/exception/domain/jwt/TokenUnsupportedException.java, src/main/java/com/dongsoop/dongsoop/filter/JwtFilter.java, src/main/java/com/dongsoop/dongsoop/handler/JwtLogoutHandler.java, src/main/java/com/dongsoop/dongsoop/jwt/JwtKeyManager.java, src/main/java/com/dongsoop/dongsoop/jwt/JwtUtil.java, src/main/java/com/dongsoop/dongsoop/jwt/JwtValidator.java, src/main/java/com/dongsoop/dongsoop/jwt/TokenGenerator.java, src/main/java/com/dongsoop/dongsoop/member/entity/Member.java, src/main/java/com/dongsoop/dongsoop/member/entity/MemberDetails.java, src/main/java/com/dongsoop/dongsoop/member/entity/Role.java, src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepository.java, src/main/java/com/dongsoop/dongsoop/member/service/MemberDetailsService.java, src/main/resources/application.properties
close #2 
- 회원 클래스 구현
- PostgreSQL 연동
- Spring Security 설정
- JWT Filter 설정
- Logout handler 구현
- 사용자 지정 예외 처리 구현
- JWT 관련 유틸 기능 구현
=> feat: 회원 및 요청에 대한 권한 확인 처리

src/main/java/com/dongsoop/dongsoop/jwt/JwtValidator.java
토큰 발급 로직에 not 연산자가 누락된 문제 해결
```java
if (StringUtils.hasText(token)) { // 토큰이 존재할 때 예외
throw new TokenMalformedException();
}
if (!StringUtils.hasText(token)) { // 토큰이 존재하지 않을 때 예외를 던지도록 개선
throw new TokenMalformedException();
}
```
=> 토큰 검증 버그 수정

src/main/java/com/dongsoop/dongsoop/department/entity/Department.java, src/main/java/com/dongsoop/dongsoop/department/entity/DepartmentType.java, src/main/java/com/dongsoop/dongsoop/department/repository/DepartmentRepository.java, src/main/java/com/dongsoop/dongsoop/department/service/DepartmentService.java, src/main/java/com/dongsoop/dongsoop/department/service/DepartmentServiceImpl.java, src/main/java/com/dongsoop/dongsoop/exception/domain/department/DepartmentNotFoundException.java, src/main/java/com/dongsoop/dongsoop/exception/domain/notice/NoticeParsingException.java, src/main/java/com/dongsoop/dongsoop/member/dto/SignupRequest.java, src/main/java/com/dongsoop/dongsoop/member/entity/Member.java, src/main/java/com/dongsoop/dongsoop/member/service/MemberService.java, src/main/java/com/dongsoop/dongsoop/notice/controller/NoticeController.java, src/main/java/com/dongsoop/dongsoop/notice/dto/NoticeMaxIdByType.java, src/main/java/com/dongsoop/dongsoop/notice/entity/Notice.java, src/main/java/com/dongsoop/dongsoop/notice/repository/NoticeRepository.java, src/main/java/com/dongsoop/dongsoop/notice/service/NoticeSchedulerImpl.java, src/main/java/com/dongsoop/dongsoop/notice/service/NoticeService.java, src/main/java/com/dongsoop/dongsoop/notice/service/NoticeServiceImpl.java, src/test/java/com/dongsoop/dongsoop/notice/NoticeCrawlingTest.java
Close #15
- department, departmentType 클래스 entity 패키지 안으로 이동
- Member 클래스 내 department field의 클래스를 Department(entity)로 수정
- Member 클래스 내 createdAt field DB 필드명 수정 createdAt -> created_at
- SignupRequest 내 department field의 클래스를 DepartmentType(enum)으로 수정
- SignupRequest 내 `toEntity()` 메서드 제거
- MemberService 내 SignupRequest(dto) to Member(entity) 변환 메서드 추가
- DepartmentRepository 내 Department 프록시 객체 생성 로직 구현
- DepartmentType에 대해 실제 DB 저장 여부 확인 로직 구현 (+ DepartmentService)
=> [FIX] 회원 가입 시 학과 매핑 문제 해결

.github/workflows/deploy.yml
aws ec2속 docker-compose파일을 동작하게 설계
=> ci: Enable docker-compose

src/main/java/com/dongsoop/dongsoop/board/Board.java, src/main/java/com/dongsoop/dongsoop/board/BoardDate.java, src/main/java/com/dongsoop/dongsoop/board/RecruitmentBoard.java, src/main/java/com/dongsoop/dongsoop/common/BaseEntity.java, src/main/java/com/dongsoop/dongsoop/tutoring/entity/BoardRecruitmentStatus.java, src/main/java/com/dongsoop/dongsoop/tutoring/entity/TutoringBoard.java
- 공통 게시판 정보를 담은 Board 클래스 구현
- 모집 게시판 정보를 담은 RecruitmentBoard 클래스 구현
- 튜터링 모집 게시판에 필요한 정보를 담은 TutoringBoard 클래스 구현
- 위 3 클래스에 대해 TutoringBoard 클래스가 RecruitmentBoard를 확장, RecruitmentBoard 클래스가 Board를 확장하도록 설계
=> 튜터링 모집 게시판 엔티티 설계 구현

src/main/java/com/dongsoop/dongsoop/notice/service/NoticeSchedulerImpl.java
- 매일 정해진 시간에 자동으로 공지사항 크롤링
- 시간대 동기화 문제 해결
=> fix: add automatic notice crawling scheduler with timezone sync

src/main/java/com/dongsoop/dongsoop/member/dto/SignupRequest.java
=> 사용자 등록 시 학번입력 선택 사항으로 수정

src/main/java/com/dongsoop/dongsoop/member/controller/MemberController.java, src/main/java/com/dongsoop/dongsoop/member/dto/LoginDetails.java, src/main/java/com/dongsoop/dongsoop/member/dto/LoginMemberDetails.java, src/main/java/com/dongsoop/dongsoop/member/dto/LoginResponse.java, src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepositoryCustom.java, src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepositoryCustomImpl.java, src/main/java/com/dongsoop/dongsoop/member/service/MemberService.java, src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
로그인 시 응답되는 데이터가 추가됩니다.
- id
- nickname
- email
- department
=> 로그인 응답 데이터 추가

src/main/java/com/dongsoop/dongsoop/member/controller/MemberController.java, src/main/java/com/dongsoop/dongsoop/member/dto/LoginDetails.java, src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
Member에 주입되었던 
jwt.dto.IssuedToken -> TokenIssueResponse으로 변경
=> refactor: modify dto file path in jwt

src/main/java/com/dongsoop/dongsoop/member/controller/MemberController.java, src/main/java/com/dongsoop/dongsoop/member/dto/LoginDetails.java, src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
=> Revert "refactor: modify dto file path in jwt"

.github/workflows/deploy.yml
현재 main으로 push 동작만 빌드검사 진행 -> Pull Request시에도 빌드 검사를 진행하도록 트리거 추가
=> ci : Adding Pull Request Action Triggers

src/main/java/com/dongsoop/dongsoop/common/PageableUtil.java, src/main/java/com/dongsoop/dongsoop/department/entity/Department.java, src/main/java/com/dongsoop/dongsoop/exception/domain/study/StudyBoardNotFound.java, src/main/java/com/dongsoop/dongsoop/study/controller/StudyBoardController.java, src/main/java/com/dongsoop/dongsoop/study/dto/CreateStudyBoardRequest.java, src/main/java/com/dongsoop/dongsoop/study/dto/StudyBoardDetails.java, src/main/java/com/dongsoop/dongsoop/study/dto/StudyBoardOverview.java, src/main/java/com/dongsoop/dongsoop/study/entity/StudyBoard.java, src/main/java/com/dongsoop/dongsoop/study/entity/StudyBoardApplication.java, src/main/java/com/dongsoop/dongsoop/study/entity/StudyBoardDepartment.java, src/main/java/com/dongsoop/dongsoop/study/repository/StudyBoardDepartmentRepository.java, src/main/java/com/dongsoop/dongsoop/study/repository/StudyBoardRepository.java, src/main/java/com/dongsoop/dongsoop/study/repository/StudyBoardRepositoryCustom.java, src/main/java/com/dongsoop/dongsoop/study/repository/StudyBoardRepositoryCustomImpl.java, src/main/java/com/dongsoop/dongsoop/study/service/StudyBoardService.java, src/main/java/com/dongsoop/dongsoop/study/service/StudyBoardServiceImpl.java, src/main/java/com/dongsoop/dongsoop/tutoring/repository/TutoringBoardRepositoryCustomImpl.java, src/test/java/com/dongsoop/dongsoop/studyBoard/StudyBoardCreateTest.java, src/test/java/com/dongsoop/dongsoop/studyBoard/StudyBoardRecruitDateTest.java, src/test/java/com/dongsoop/dongsoop/studyBoard/StudyBoardStartAtTest.java, src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardRecruitDateTest.java, src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardStartAtTest.java
Close #46 
스터디 모집 게시판의 게시글 생성과 조회 기능 구현
- 게시글 목록 조회(Overview)
- 특정 게시글 세부 조회(Detail)
- 게시글 생성
- 날짜 검증
- 시작일 검증(신청일을 포함한 이후 3개월까지)
- 종료일 검증(시작일보다 미래인지)
기능 테스트
- 모집 시작일 및 종료일 검증
- 게시글 생성 테스트
=> 스터디 모집 게시판 기본 기능

src/main/java/com/dongsoop/dongsoop/exception/domain/project/ProjectBoardNotFound.java, src/main/java/com/dongsoop/dongsoop/project/controller/ProjectBoardController.java, src/main/java/com/dongsoop/dongsoop/project/dto/CreateProjectBoardRequest.java, src/main/java/com/dongsoop/dongsoop/project/dto/ProjectBoardDetails.java, src/main/java/com/dongsoop/dongsoop/project/dto/ProjectBoardOverview.java, src/main/java/com/dongsoop/dongsoop/project/entity/ProjectBoard.java, src/main/java/com/dongsoop/dongsoop/project/entity/ProjectBoardApplication.java, src/main/java/com/dongsoop/dongsoop/project/entity/ProjectBoardDepartment.java, src/main/java/com/dongsoop/dongsoop/project/repository/ProjectBoardDepartmentRepository.java, src/main/java/com/dongsoop/dongsoop/project/repository/ProjectBoardRepository.java, src/main/java/com/dongsoop/dongsoop/project/repository/ProjectBoardRepositoryCustom.java, src/main/java/com/dongsoop/dongsoop/project/repository/ProjectBoardRepositoryCustomImpl.java, src/main/java/com/dongsoop/dongsoop/project/service/ProjectBoardService.java, src/main/java/com/dongsoop/dongsoop/project/service/ProjectBoardServiceImpl.java, src/test/java/com/dongsoop/dongsoop/projectBoard/ProjectBoardCreateTest.java, src/test/java/com/dongsoop/dongsoop/projectBoard/ProjectBoardRecruitDateTest.java, src/test/java/com/dongsoop/dongsoop/projectBoard/ProjectBoardStartAtTest.java
Close #52 
프로젝트 모집 게시판의 게시글 생성과 조회 기능 구현
게시글 목록 조회(Overview)
특정 게시글 세부 조회(Detail)
게시글 생성
날짜 검증
시작일 검증(신청일을 포함한 이후 3개월까지)
종료일 검증(시작일보다 미래인지)
기능 테스트
모집 시작일 및 종료일 검증
게시글 생성 테스트
=> 프로젝트 모집 게시판 기능 구현

src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java, src/main/java/com/dongsoop/dongsoop/chat/dto/ReadStatusUpdateRequest.java, src/main/java/com/dongsoop/dongsoop/chat/entity/ChatMessage.java, src/main/java/com/dongsoop/dongsoop/chat/entity/ChatRoom.java, src/main/java/com/dongsoop/dongsoop/chat/entity/ChatRoomInitResponse.java, src/main/java/com/dongsoop/dongsoop/chat/entity/IncrementalSyncResponse.java, src/main/java/com/dongsoop/dongsoop/chat/repository/RedisChatRepository.java, src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java, src/main/java/com/dongsoop/dongsoop/chat/service/ChatSyncService.java, src/main/java/com/dongsoop/dongsoop/chat/service/ReadStatusService.java, src/main/java/com/dongsoop/dongsoop/chat/validator/ChatValidator.java, src/main/java/com/dongsoop/dongsoop/config/RedisConfig.java
#77
이슈확인
- 사용자 참가 시점 이후 메시지 조회
- 특정 메시지 ID 이후 메시지 조회
1. Redis Sorted Set 도입으로 성능 최적화
기존 문제: Redis List를 사용하여 매번 전체 메시지를 가져온 후 애플리케이션에서 필터링
개선 방안: Redis Sorted Set(ZSET) 도입으로 Redis 레벨에서 직접 시간/범위 기반 조회
네트워크 비용: 90% 절감 (1000개 중 100개 필요 시, 1000개 → 100개만 전송)
메모리 사용량: 대폭 감소 (Redis에서 필터링하므로 불필요한 데이터 로드 없음)
응답 시간: O(N) → O(log N + M) 복잡도 개선
=> 채팅 메시지 증분 동기화 기능 추가

src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
이전에 있던 특정방에 어떠한 사용자가 있는지 반환하는 API 추가
=> feat: Add chat room participant nickname return api

src/test/java/com/dongsoop/dongsoop/projectBoard/ProjectRecruitmentDepartmentEligibilityValidatorTest.java, src/test/java/com/dongsoop/dongsoop/studyBoard/StudyRecruitmentDepartmentEligibilityValidatorTest.java, src/test/java/com/dongsoop/dongsoop/tutoring/TutoringRecruitmentDepartmentEligibilityValidatorTest.java
모집(튜터링, 스터디, 프로젝트) 게시글에 대하여 참여 시 사용자 학과와 모집 학과 검증 테스트 코드에서  
이미 지원한 경우에 대한 추가 로직이 처리되지 않아 테스트가 실패하는 문제
지원 여부에 대해 항상 `false`를 반환하도록 Mock
```java
when(studyApplyRepositoryCustom.existsByBoardIdAndMemberId(boardId, null)) // null은 회원 ID를 의미
.thenReturn(false);
```
=> 검증 절차 추가에 따른 테스트 케이스 Mock 추가

src/main/java/com/dongsoop/dongsoop/marketplace/dto/MarketplaceBoardDetails.java, src/main/java/com/dongsoop/dongsoop/marketplace/entity/MarketplaceBoard.java, src/main/java/com/dongsoop/dongsoop/marketplace/repository/MarketplaceBoardRepository.java, src/main/java/com/dongsoop/dongsoop/marketplace/repository/MarketplaceBoardRepositoryCustomImpl.java, src/main/java/com/dongsoop/dongsoop/marketplace/service/MarketplaceBoardServiceImpl.java
장터 게시판 기능에서 일부가 수정되었습니다.
- 세부 게시글 정보 조회 시 status(OPEN, CLOSED)가 추가됩니다.
- status가 DB에 STRING 형식으로 저장됩니다.
- 게시글 CLOSE 시 요청자 ID 검증이 추가됩니다.
=> 장터 게시판 리팩터링

src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
응답 바디가 존재하지 않는 OK(200) 응답에 대해 NoContent(201) 응답으로 수정하였습니다.
=> OK 응답에 대해 No Content로 수정

src/main/java/com/dongsoop/dongsoop/recruitment/apply/dto/ApplyDetails.java, src/main/java/com/dongsoop/dongsoop/recruitment/apply/projection/ProjectRecruitmentApplyProjection.java, src/main/java/com/dongsoop/dongsoop/recruitment/apply/projection/StudyRecruitmentApplyProjection.java, src/main/java/com/dongsoop/dongsoop/recruitment/apply/projection/TutoringRecruitmentApplyProjection.java
모집 지원자 상세 조회 시 제목이 포함됩니다.
```json
{
"boardId": 2,
"title": "알고리즘 튜터 모집",
"applierId": 2,
"applierName": "bob",
"departmentName": "기계공학과",
"applyTime": "2025-05-20T00:00:00",
"introduction": "자기소개",
"motivation": "지원동기"
}
```
=> 모집 지원자 상세 조회 시 제목 포함

src/main/java/com/dongsoop/dongsoop/recruitment/board/project/controller/ProjectBoardController.java, src/main/java/com/dongsoop/dongsoop/recruitment/board/project/entity/ProjectBoard.java, src/main/java/com/dongsoop/dongsoop/recruitment/board/project/service/ProjectBoardService.java, src/main/java/com/dongsoop/dongsoop/recruitment/board/project/service/ProjectBoardServiceImpl.java, src/main/java/com/dongsoop/dongsoop/recruitment/board/study/controller/StudyBoardController.java, src/main/java/com/dongsoop/dongsoop/recruitment/board/study/entity/StudyBoard.java, src/main/java/com/dongsoop/dongsoop/recruitment/board/study/service/StudyBoardService.java, src/main/java/com/dongsoop/dongsoop/recruitment/board/study/service/StudyBoardServiceImpl.java, src/main/java/com/dongsoop/dongsoop/recruitment/board/tutoring/controller/TutoringBoardController.java, src/main/java/com/dongsoop/dongsoop/recruitment/board/tutoring/entity/TutoringBoard.java, src/main/java/com/dongsoop/dongsoop/recruitment/board/tutoring/service/TutoringBoardService.java, src/main/java/com/dongsoop/dongsoop/recruitment/board/tutoring/service/TutoringBoardServiceImpl.java
생성한 모집 게시글에 대해 삭제할 수 있습니다.
- 게시글 주인 검증
- 삭제 시 is_deleted 필드 true로 수정
> [!NOTE]
> /tutoring-board/{boardId}
> /study-board/{boardId}
> /project-board/{boardId}
> 204 NoContent
=> 모집 게시판 삭제 기능

src/main/java/com/dongsoop/dongsoop/report/dto/ReportSummaryResponse.java, src/main/java/com/dongsoop/dongsoop/report/repository/ReportRepositoryCustomImpl.java
관리자가 미처리 신고를 확인할 때 제재 처리에 필요한 정보를 바로 볼 수 있도록 API 응답 구조를 개선
- targetMemberId 필드 추가: 제재 처리 시 POST /reports/sanctions에서 사용
- description 필드 추가: 관리자 UI에서 신고 내용 표시용
- createSummaryProjection(): 새 필드들을 projection에 추가
- createSummaryBaseQuery(): targetMember 테이블 조인 추가
- 미처리 신고 조회 시 필요한 정보를 모두 포함하도록 개선
=> 신고 확인시 필요한 응답 구조 개선

src/main/java/com/dongsoop/dongsoop/common/config/QuerydslConfig.java, src/main/java/com/dongsoop/dongsoop/member/dto/LoginMemberDetails.java, src/main/java/com/dongsoop/dongsoop/member/dto/LoginResponse.java, src/main/java/com/dongsoop/dongsoop/member/exception/MemberRoleNotAvailableException.java, src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepositoryCustomImpl.java
회원 로그인 시 회원이 가진 권한(Role)을 함꼐 응답합니다.
```json
{
"id": 1,
"accessToken": "...",
"refreshToken": "...",
"nickname": "...",
"email": "...",
"departmentType": "...",
"role": [
"USER",
"ADMIN"
]
}
```
=> 회원 권한 로그인 응답 값에 포함

src/main/java/com/dongsoop/dongsoop/report/dto/ReportSummaryResponse.java, src/main/java/com/dongsoop/dongsoop/report/repository/ReportRepositoryCustomImpl.java
- /reports/admin?filter=UNPROCESSED
요약정보 응답값 필드에 신고를 당한 게시글의 ID필드를 추가하였습니다.
=> feat(Report): Add Id field of reported post

src/main/java/com/dongsoop/dongsoop/mailverify/service/MailTextGeneratorImpl.java
기존 로그 확인을 위해 추가한 커밋을 revert한 커밋을 추가하였습니다.
=> 로그 커밋 revert

src/main/java/com/dongsoop/dongsoop/notice/service/NoticeSchedulerImpl.java, src/main/resources/logback.xml
로그가 파일로 저장될 때 비동기적으로 처리됩니다.
또한 공지사항 크롤링 처리 시간 확인을 위해 3시를 추가하였습니다.
=> 로그 파일 저장 방식 비동기 처리

src/main/java/com/dongsoop/dongsoop/jwt/handler/JwtLogoutHandler.java
로그아웃 시 등록된 JwtFilter를 거치지 않아, Security Context에 정보가 등록되지 않는 문제를 해결했습니다.  
LogoutHandler에서 해당 request를 검사하고, 토큰을 꺼내어 직접 확인합니다.
=> hotfix: 로그아웃 시 사용자 인증 정보 확인

src/main/java/com/dongsoop/dongsoop/notice/controller/NoticeController.java, src/main/java/com/dongsoop/dongsoop/notice/service/NoticeSchedulerImpl.java, src/main/java/com/dongsoop/dongsoop/role/entity/RoleType.java
학과 공지 크롤링 시 최신 공지 번호 확인을 위한 로그를 추가하였습니다.
=> log: logging notice recent number for crawl each department notices

src/main/java/com/dongsoop/dongsoop/recruitment/apply/notification/RecruitmentApplyNotification.java
모집 게시글 지원 시 알림 전송이 누락되어 포함하였습니다.
=> 지원자 알림 누락 추가

src/main/java/com/dongsoop/dongsoop/DongsoopApplication.java, src/main/java/com/dongsoop/dongsoop/chat/notification/ChatNotificationImpl.java, src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepository.java, src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepositoryCustom.java, src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepositoryCustomImpl.java, src/main/java/com/dongsoop/dongsoop/memberdevice/service/MemberDeviceService.java, src/main/java/com/dongsoop/dongsoop/memberdevice/service/MemberDeviceServiceImpl.java, src/main/java/com/dongsoop/dongsoop/notice/notification/NoticeNotificationImpl.java, src/main/java/com/dongsoop/dongsoop/notice/service/NoticeSchedulerImpl.java, src/main/java/com/dongsoop/dongsoop/notification/controller/NotificationController.java, src/main/java/com/dongsoop/dongsoop/notification/dto/NotificationList.java, src/main/java/com/dongsoop/dongsoop/notification/dto/NotificationOverview.java, src/main/java/com/dongsoop/dongsoop/notification/dto/NotificationUnread.java, src/main/java/com/dongsoop/dongsoop/notification/repository/NotificationRepositoryCustom.java, src/main/java/com/dongsoop/dongsoop/notification/repository/NotificationRepositoryCustomImpl.java, src/main/java/com/dongsoop/dongsoop/notification/service/FCMService.java, src/main/java/com/dongsoop/dongsoop/notification/service/FCMServiceImpl.java, src/main/java/com/dongsoop/dongsoop/notification/service/NotificationService.java, src/main/java/com/dongsoop/dongsoop/notification/service/NotificationServiceImpl.java, src/main/java/com/dongsoop/dongsoop/recruitment/apply/notification/RecruitmentApplyNotification.java, src/main/java/com/dongsoop/dongsoop/recruitment/apply/project/notification/ProjectApplyNotification.java, src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/notification/StudyApplyNotification.java, src/main/java/com/dongsoop/dongsoop/recruitment/apply/tutoring/notification/TutoringApplyNotification.java
기존 알림 목록을 조회할 때, 페이징과 관계 없이 읽지 않은 모든 알림의 수를 반환합니다.  
추가로 앱 아이콘에 알림 뱃지가 추가됩니다.
=> 알림 목록 조회 시 읽지 않은 알림 수 포함

src/main/java/com/dongsoop/dongsoop/calendar/controller/ScheduleController.java, src/main/java/com/dongsoop/dongsoop/calendar/service/ScheduleService.java, src/main/java/com/dongsoop/dongsoop/calendar/service/ScheduleServiceImpl.java, src/main/java/com/dongsoop/dongsoop/member/service/MemberService.java, src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
-
- 비회원도 학사 일정을 바로 확인할 수 있도록 정책 설정
3분
=> 비회원 학사일정 조회

src/main/java/com/dongsoop/dongsoop/chat/util/ChatCommonUtils.java
=> fix: handle null RecruitmentType in createContactMappingKey

README.md
=> feat: Project Description
