dongsooop/backend

src/main/java/com/dongsoop/dongsoop/member/entity/Member.java

- createdAt 초기화 방식 수정
- builder 패턴에 따른 createdAt 필드 초기화가 되지 않는 문제
- PrePersist를 통해 회원 저장시 자동 주입
- 학과 컬럼명에 `_id`추가

회원 테이블 컬럼 수정

---

src/main/java/com/dongsoop/dongsoop/common/BaseEntity.java
src/main/java/com/dongsoop/dongsoop/member/entity/Member.java

Soft Delete 구현을 위한 BaseEntity 구현

---

build.gradle
src/main/resources/logback.xml

- Logback 설정 파일에 Discord 웹훅 어펜더 추가
- ERROR 레벨 이상의 로그만 Discord로 전송되도록 필터링 설정
- 비동기 처리를 통한 서버 성능 영향 최소화
- 타임스탬프, 스레드, 로그 레벨 및 전체 스택 트레이스가 포함된 포맷 적용
- Discord 로깅 기능을 위한 외부 라이브러리 의존성 추가 (logback-discord-appender)

서버에서 발생하는 에러 로그를 Discord Web Hook을 통해 실시간 전송 기능 구현

---

src/main/java/com/dongsoop/dongsoop/DongsoopApplication.java
src/main/java/com/dongsoop/dongsoop/board/Board.java
src/main/java/com/dongsoop/dongsoop/common/BaseEntity.java
src/main/java/com/dongsoop/dongsoop/tutoring/repository/TutoringBoardRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/tutoring/service/TutoringBoardServiceImpl.java
src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardCreateTest.java

- Board 클래스 내 createdAt, updatedAt 필드를 BaseEntity로 이동
- createdAt과 updatedAt을 각 이벤트에 맞게 초기화 되고, 업데이트 되도록 설정

데이터 생성일자 및 수정일 위치 수정

---

src/main/java/com/dongsoop/dongsoop/DongsoopApplication.java
src/main/java/com/dongsoop/dongsoop/config/JpaAuditingConfig.java

Close #33 
`@EnableJpaAuditing`을 Application 클래스에 선언하여 발생한 문제입니다.
정확하게는 WebMvcTest 테스트 환경에서는 Spring MVC(컨트롤러 등)와 관련된 빈만 로드하는 슬라이스 테스트로,
이 테스트에서는 JPA 관련 Entity, Repository 등의 빈은 로드되지 않습니다.  
그런데 Application에 `@EnableJpaAuditing` 가 정의되어 JPA 관련 빈을 필요로 하게 되어 발생한 문제입니다.
위 문제를 Application이 아닌 별도 `@Configuration` 클래스로 분리하여 해결하였습니다.
WebMvcTest는 Application 클래스를 기준으로 로드하기에 분리된 클래스는 로드하지 않아 해결되었습니다.

JPA Auditing 설정 위치에 따른 컨트롤러 테스트 실패 문제 개선

---

src/main/java/com/dongsoop/dongsoop/board/RecruitmentBoard.java
src/main/java/com/dongsoop/dongsoop/tutoring/dto/CreateTutoringBoardRequest.java
src/main/java/com/dongsoop/dongsoop/tutoring/dto/TutoringBoardDetails.java
src/main/java/com/dongsoop/dongsoop/tutoring/dto/TutoringBoardOverview.java
src/main/java/com/dongsoop/dongsoop/tutoring/repository/TutoringBoardRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/tutoring/service/TutoringBoardServiceImpl.java
src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardCreateTest.java
src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardRecruitDateTest.java
src/test/java/com/dongsoop/dongsoop/tutoring/TutoringBoardStartAtTest.java

- 튜터링 상세 정보 반환 시 생성일자를 제거하고 시작일자를 포함한 정보 응답
- 모집 정원 필드 제거

튜터링 게시글 응답 정보 수정

---

src/main/java/com/dongsoop/dongsoop/exception/domain/notice/NoticeSubjectNotAvailableException.java
src/main/java/com/dongsoop/dongsoop/notice/util/NoticeParser.java

- 공지사항 크롤링 시 `td-subject` 클래스 내 `strong` 태그가 존재하는지 확인
- strong 태그가 존재한다면 strong태그의 내용만 가져오도록 수정
- strong 태그가 없는 경우 기존과 같이 td-subject 내 텍스트를 가져오도록 작업

숨겨진(불필요한) 텍스트 크롤링 대상에서 제외

---

src/main/java/com/dongsoop/dongsoop/exception/GlobalExceptionHandler.java
src/main/java/com/dongsoop/dongsoop/exception/domain/jwt/TokenMalformedException.java
src/main/java/com/dongsoop/dongsoop/jwt/filter/JwtFilter.java

JWT Filter에서 사용자 토큰 검증 시 예외가 발생한다면 Spring MVC 레이어로 예외 처리를 위임하여 Response를 생성하도록 수정되었습니다.
- 전역 예외처리의 중복 코드를 메서드로 분리하였습니다.
- 일반 예외(ex. IllegalArgsException)에 대해 일관된 응답을 처리하는 코드를 추가했습니다.

JWT Filter 레이어 예외처리

---

src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
src/main/java/com/dongsoop/dongsoop/chat/controller/ChatSocketController.java
src/main/java/com/dongsoop/dongsoop/chat/dto/KickUserRequest.java
src/main/java/com/dongsoop/dongsoop/chat/entity/ChatMessage.java
src/main/java/com/dongsoop/dongsoop/chat/entity/ChatMessageEntity.java
src/main/java/com/dongsoop/dongsoop/chat/entity/ChatRoom.java
src/main/java/com/dongsoop/dongsoop/chat/repository/InMemoryChatRepository.java
src/main/java/com/dongsoop/dongsoop/chat/repository/RedisChatRepository.java
src/main/java/com/dongsoop/dongsoop/chat/service/ChatBackupService.java
src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
src/main/java/com/dongsoop/dongsoop/chat/validator/ChatValidator.java
src/main/java/com/dongsoop/dongsoop/member/service/MemberService.java
src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java

- 그룹채팅방 매니저 권한의 강퇴기능의 로직 수정
- 1:1채팅방, 그룹채팅방인지 설정하는 로직보강
- 사용자의 닉네임 필드 삭제 -> Id로 변경

채팅 매니저 권한 로직 추가 및 사용자 닉네임 필드삭제

---

src/main/java/com/dongsoop/dongsoop/recruitment/project/controller/ProjectBoardController.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/dto/ProjectBoardOverview.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectBoardService.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectBoardServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/controller/StudyBoardController.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/dto/StudyBoardOverview.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyBoardService.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyBoardServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/controller/TutoringBoardController.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/dto/TutoringBoardOverview.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringBoardService.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringBoardServiceImpl.java

Close #73 
비회원의 경우 학과가 설정되어있지 않아, 전체 학과를 대상으로한 학습 구성원 모집 게시글 목록을 조회할 수 있도록 기능 추가

학습 구성원 모집 게시글 전체 학과 대상 목록 조회 기능 구현

---

src/main/java/com/dongsoop/dongsoop/exception/domain/authentication/NotAuthenticationException.java
src/main/java/com/dongsoop/dongsoop/exception/domain/project/ProjectRecruitmentAlreadyAppliedException.java
src/main/java/com/dongsoop/dongsoop/exception/domain/study/StudyRecruitmentAlreadyAppliedException.java
src/main/java/com/dongsoop/dongsoop/exception/domain/tutoring/TutoringRecruitmentAlreadyAppliedException.java
src/main/java/com/dongsoop/dongsoop/member/service/MemberService.java
src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/dto/ProjectBoardDetails.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectApplyRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectApplyRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepository.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectBoardRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectApplyServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectBoardServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/dto/StudyBoardDetails.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyApplyRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyApplyRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepository.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyBoardRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyApplyServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyBoardServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/dto/TutoringBoardDetails.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringApplyRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringApplyRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepository.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringBoardRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringApplyServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringBoardServiceImpl.java

모집 게시글 상세페이지 접근 시 지원 여부에 따라 버튼 상태를 달리 하기 위한 구현  
아래와 같이 게시판, 사용자 레퍼런스 엔티티를 통해 존재 여부 확인 후 응답에 포함
```java
StudyBoard board = studyBoardRepository.getReferenceById(boardId);
StudyApplyKey applyKey = new StudyApplyKey(board, member);
boolean isAlreadyApplied = studyApplyRepository.existsById(applyKey);
```
\+ 중복 지원 시 오류를 반환합니다. - 400 Bad Request

모집 게시글 상세페이지 내 지원 여부 반환

---

src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java

#왜 필요한가?
변경전 로직에서는 채팅방 개설 시 초기 참가자의 입장에 대한 시스템 메세지를 반환하는데, 
현재 발견된 문제는 활동중인 채팅방에 새로운 참가자를 초대한뒤 입장시에 enter메세지와 사용자 입장을 알리는 id값을 반환 되어야 정상적인 로직인데 해당 기능이 정상적으로 동작하지않아 수정 및 추가하였습니다.
새로 초대된 사용자인지 판단하는 로직
사용자의 입장 시간이 채팅방 생성 시간보다 늦은지 확인
이전 ENTER 메시지 이력 체크
해당 사용자의 이전 ENTER 메시지 존재 여부 확인
중복 ENTER 메시지 생성 방지
isFirstTimeEntry 메서드 개선
기존 로직에 새로 초대된 사용자 판단 로직 추가
Objects.isNull(userJoinTime) || isNewInvitedUser(...) 조건으로 변경

활동 중인 채팅방에 새로 초대된 사용자 판단 기능 추가

---

src/main/java/com/dongsoop/dongsoop/recruitment/validation/annotation/BoardTag.java

- `,`를 기준으로 나눠야 하나, `@Pattern` 어노테이션에서 `,`를 포함하지 않는 문제 개선
- `^[a-zA-Z0-9가-힣]+[a-zA-Z0-9가-힣,]*$`
- Validator 방식을 통해 request 시 값을 검증해야 하지만 `@BoardTag`에서 Validator에 필요한 필드 값 정의가 되어있지 않은 문제 개선
```java
String message() default "태그는 한글, 영문, 숫자만 포함할 수 있으며 쉼표(,)를 포함한 최대 100자입니다";
Class<?>[] groups() default {};
Class<? extends Payload>[] payload() default {};
```

모집 게시글 생성 시 필요한 태그에 대해 어노테이션 문제 개선

---

src/main/java/com/dongsoop/dongsoop/common/BaseEntity.java
src/main/java/com/dongsoop/dongsoop/member/controller/MemberController.java
src/main/java/com/dongsoop/dongsoop/member/entity/Member.java
src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepository.java
src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/member/repository/MemberRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/member/service/MemberService.java
src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java

회원 탈퇴는 가명 처리를 통해 기존 게시글 데이터는 삭제되지 않도록 처리했습니다.
- BaseEntity 클래스의 필드를 protected로 설정하여 상속받는 클래스에서 접근이 가능하도록 수정되었습니다.
- 회원 탈퇴용 API를 추가하였습니다.
- 가명 처리 방식의 회원 탈퇴 로직 추가에 따라 로그인 시 탈퇴여부를 검증하는 로직이 추가되었습니다.
- 탈퇴된 회원이 작성한 글에 대해 가명으로 노출하기 위해 `@SQLRestriction("is_deleted = false")`를 제거하였습니다.

회원 탈퇴 기능 구현

---

src/main/java/com/dongsoop/dongsoop/recruitment/dto/ApplyDetails.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/controller/ProjectApplyController.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/exception/ProjectApplyNotFoundException.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectApplyRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/repository/ProjectApplyRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectApplyService.java
src/main/java/com/dongsoop/dongsoop/recruitment/project/service/ProjectApplyServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/projection/ProjectRecruitmentProjection.java
src/main/java/com/dongsoop/dongsoop/recruitment/projection/RecruitmentProjection.java
src/main/java/com/dongsoop/dongsoop/recruitment/projection/StudyRecruitmentProjection.java
src/main/java/com/dongsoop/dongsoop/recruitment/projection/TutoringRecruitmentProjection.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/controller/StudyApplyController.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/exception/StudyApplyNotFoundException.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyApplyRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/repository/StudyApplyRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyApplyService.java
src/main/java/com/dongsoop/dongsoop/recruitment/study/service/StudyApplyServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/controller/TutoringApplyController.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/exception/TutoringApplyNotFoundException.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringApplyRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/repository/TutoringApplyRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringApplyService.java
src/main/java/com/dongsoop/dongsoop/recruitment/tutoring/service/TutoringApplyServiceImpl.java

Close #113 
개설한 모집 글에 대해 지원한 지원자의 닉네임과 같은 회원 정보를 비롯하여  
지원 시 작성한 자기소개, 지원동기를 반환합니다.
- 통합 조회 메서드가 UNION 메서드 사용으로 인해 JpaRepository에서 관리되기 때문에 Projection이 의미가 사라짐

모집 게시글 지원자 세부 지원 정보 조회

---

src/main/java/com/dongsoop/dongsoop/member/service/MemberServiceImpl.java

회원 탈퇴 시 가명처리 과정에서 DB에 제한된 범위를 넘는 가명을 저장하여 쿼리 에러가 발생하는 문제를 해결했습니다.  
> 이메일은 50글자 제한이지만, 기존 인코딩 방식은 60글자를 제한했었습니다.
```java
String emailAlias = passwordEncoder.encode(UUID.randomUUID().toString());
String emailAlias = UUID.randomUUID().toString().replace("-", "");
```

회원탈퇴 불가 문제 수정

---

src/main/java/com/dongsoop/dongsoop/recruitment/board/dto/RecruitmentDetails.java

모집 게시글 상세 조회 시 학과가 중복 조회되는 문제를 distinct() 메서드를 통해 해결하였습니다.

DB 조회 결과 중복 제거

---

src/main/java/com/dongsoop/dongsoop/jwt/JwtUtil.java
src/main/java/com/dongsoop/dongsoop/jwt/exception/JWTException.java
src/main/java/com/dongsoop/dongsoop/jwt/exception/NotAccessTokenException.java
src/main/java/com/dongsoop/dongsoop/jwt/exception/NotRefreshTokenException.java
src/main/java/com/dongsoop/dongsoop/jwt/exception/RefreshTokenNotFoundException.java
src/main/java/com/dongsoop/dongsoop/jwt/exception/TokenExpiredException.java
src/main/java/com/dongsoop/dongsoop/jwt/exception/TokenMalformedException.java
src/main/java/com/dongsoop/dongsoop/jwt/exception/TokenNotFoundException.java
src/main/java/com/dongsoop/dongsoop/jwt/exception/TokenRoleNotAvailableException.java
src/main/java/com/dongsoop/dongsoop/jwt/exception/TokenSignatureException.java
src/main/java/com/dongsoop/dongsoop/jwt/exception/TokenUnsupportedException.java
src/main/java/com/dongsoop/dongsoop/jwt/filter/JwtFilter.java

필터에서 사용자 JWT 검증 시 토큰에 문제(만료, 시그니처 오류 등)가 있는 경우 401 예외를 발생시키도록 수정하였습니다.  
토큰이 존재하지 않는 경우는 여전히 `익명`사용자로 등록되어 컨트롤러 로직을 수행하며,  
토큰이 정상적인 경우에도 권한이 정상 등록되어 실행됩니다.

필터 토큰 검증 로직 수정

---

src/main/java/com/dongsoop/dongsoop/board/RecruitmentBoard.java
src/main/java/com/dongsoop/dongsoop/recruitment/validation/annotation/BoardTag.java
src/main/java/com/dongsoop/dongsoop/recruitment/validation/annotation/BoardTagValidator.java
src/main/java/com/dongsoop/dongsoop/recruitment/validation/constant/RecruitmentValidationConstant.java

모집 게시글 생성 시 태그를 필수로 등록하도록 강제합니다.  
- 요청 시 `@Valid`를 통해 `태그,태그` 형태의 구조를 검사합니다.
- DB 저장 시 `nullable = false`를 통해 검사합니다.

모집 게시글 태그 필수 적용

---

src/main/java/com/dongsoop/dongsoop/notice/util/NoticeLinkParser.java

대학 홈페이지 구조 조정에 따라 대학 공지에만 추가하였던 레이아웃 헤더를 학과 공지에도 추가하였습니다.

공지사항 파싱 시 헤더 추가

---

src/main/java/com/dongsoop/dongsoop/mypage/dto/MyRecruitmentOverview.java
src/main/java/com/dongsoop/dongsoop/mypage/dto/MyRecruitmentOverviewResponse.java
src/main/java/com/dongsoop/dongsoop/mypage/dto/RecruitmentStatusType.java
src/main/java/com/dongsoop/dongsoop/recruitment/repository/RecruitmentRepository.java

마이페이지에서 일부 기능이 수정되었습니다.
- 개설한 게시물 목록 조회 시 `isRecruitment(boolean)`필드가 `status(RecruitmentStatusType)`으로 수정되었습니다.
- 이는 모집중, 모집종료 상태를 넘어 모집 대기 상태를 추가하기 위함입니다.
- 지원한 모집 게시물 목록 조회 시 `MyRecruitmentOverview` 에서 `MyRecruitmentOverviewResponse`로 수정되었습니다.
- department가 String 타입("학과1,학과2")이 아닌 List로 반환됩니다.

마이페이지 구조 수정

---

src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
src/main/java/com/dongsoop/dongsoop/chat/dto/CreateRoomRequest.java
src/main/java/com/dongsoop/dongsoop/chat/dto/InviteUserRequest.java
src/main/java/com/dongsoop/dongsoop/chat/entity/ChatRoom.java
src/main/java/com/dongsoop/dongsoop/chat/entity/ChatRoomEntity.java
src/main/java/com/dongsoop/dongsoop/chat/exception/GroupChatOnlyException.java
src/main/java/com/dongsoop/dongsoop/chat/exception/KickedUserInviteException.java
src/main/java/com/dongsoop/dongsoop/chat/exception/UserAlreadyInRoomException.java
src/main/java/com/dongsoop/dongsoop/chat/service/ChatMessageService.java
src/main/java/com/dongsoop/dongsoop/chat/service/ChatParticipantService.java
src/main/java/com/dongsoop/dongsoop/chat/service/ChatRoomService.java
src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
src/main/java/com/dongsoop/dongsoop/chat/util/ChatCommonUtils.java
src/main/java/com/dongsoop/dongsoop/chat/validator/ChatValidator.java

#135 
채팅 서비스 전반에 공용으로 사용되는 중복된 코드를 제거하고 공통 유틸리티를 통해 관리하였습니다.
- 1:1 채팅방 제목 설정 기능 추가
- CreateRoomRequest에 title 필드 추가
- ChatRoom.create() 메서드 오버로드로 title 지원
- 기존 API와 완전한 하위 호환성 유지
- ChatCommonUtils 유틸리티 클래스 신규 생성
- 사용자 ID 검증, 메시지 생성, 시간 처리 등 공통 기능 통합
- UUID 생성 및 시스템 메시지 내용 생성 중앙화
- 메시지 보강 로직 (ID, 시간, 타입) 표준화
- 이전 ChatService에 있는 로직들을 각 기능에 맞게 Message, Participant, room 서비스로 분리하였습니다.
- validatePositiveUserId(): ChatRoomService, ChatParticipantService에서 중복 제거
- generateMessageId(): ChatValidator, ChatMessageService에서 통합
- 메시지 보강 관련 메서드들: 모든 서비스에서 ChatCommonUtils 사용

그룹채팅방 초대 기능 및 서비스 구조 개선, 중복 코드 제거

---

src/main/java/com/dongsoop/dongsoop/board/Board.java
src/main/java/com/dongsoop/dongsoop/board/RecruitmentBoard.java
src/main/java/com/dongsoop/dongsoop/recruitment/apply/project/service/ProjectApplyServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/apply/study/service/StudyApplyServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/apply/tutoring/service/TutoringApplyServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/board/project/service/ProjectBoardServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/board/study/service/StudyBoardServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/board/tutoring/service/TutoringBoardServiceImpl.java

- 모집글 작성 시 자동으로 그룹 채팅방이 생성되고, 지원자 합격 시 해당 채팅방에 자동 초대되는 기능을 구현했습니다.
- RecruitmentBoard에 roomId 필드 추가
- 게시글 생성 시 자동으로 그룹 채팅방 생성
- 생성된 채팅방 ID를 게시글에 저장하여 영구 연결
- 스터디, 프로젝트, 튜터링 게시글 작성 시 각각 자동으로 채팅방 생성
- 채팅방 제목: [스터디] 게시글제목, [프로젝트] 게시글제목, [튜터링] 게시글제목
- 작성자가 자동으로 채팅방 관리자가 되어 초기 참여
- 지원자를 합격 처리하면 자동으로 해당 게시글의 채팅방에 초대
- 프론트엔드에서는 기존 합격 API만 호출하면 모든 처리 완료
- 별도의 채팅방 생성/초대 과정 불필요
- 트랜잭션 기반: 게시글 생성과 채팅방 생성을 하나의 트랜잭션으로 처리
- 에러 핸들링: 채팅방 생성 실패 시 전체 롤백으로 데이터 일관성 보장
- 확장성: 3개 모듈(Study, Project, Tutoring) 모두 동일한 패턴으로 구현
- 간소화된 UX: 게시글 작성과 동시에 채팅방 자동 생성
- 원클릭 처리: 합격 버튼 한 번으로 상태 변경 + 채팅방 초대 완료
- 일관된 경험: 모든 모집글마다 채팅방이 자동으로 존재

모집글 작성 시 자동으로 그룹 채팅방 생성 및 자동 초대 추가

---

src/main/java/com/dongsoop/dongsoop/chat/controller/ChatSocketController.java
src/main/java/com/dongsoop/dongsoop/common/config/WebSocketConfig.java

- 그룹 채팅방에 혼자 있을 때 메시지 수신이 안되는 문제
- 1:1 채팅에서 상대방이 오프라인일 때 메시지 수신이 안되는 문제
- `@SendTo` → `SimpMessagingTemplate` 사용
- 메시지 발신자 본인도 포함하여 브로드캐스트하도록 수정
- 기존 블락 상태 확인 로직은 그대로 유지
- corePoolSize: 4 → 16
- maxPoolSize: 10 → 50
- queueCapacity: 100 → 300
- 동시 접속자 증가 시 안정성 향상

fix: WebSocket 메시지 수신 안되는 문제 및 성능 개선

---

src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
src/main/java/com/dongsoop/dongsoop/chat/dto/CreateContactRoomRequest.java
src/main/java/com/dongsoop/dongsoop/chat/service/ChatRoomService.java
src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java

1. 혼자 있으면 알림 받을 사람이 없음
2. 알림 서비스 호출 자체가 불필요
3. 근본적으로 호출하지 않는 게 맞음
- 혼자 있는 방: receiver.isEmpty() → 알림 전송 안 함 → 메시지만 브로드캐스트
- 상대방 있는 방: !receiver.isEmpty() → 알림 전송 → 메시지 브로드캐스트
채팅방에 혼자 있을 시 알림 전송이 건너 뛰도록 조건을 달아서 해결했습니다.

fix: FCM 알림 실패로 인한 메시지 처리 중단 문제 해결

---

src/main/java/com/dongsoop/dongsoop/timetable/controller/TimetableController.java
src/main/java/com/dongsoop/dongsoop/timetable/repository/TimetableRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/timetable/repository/TimetableRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/timetable/service/TimetableService.java
src/main/java/com/dongsoop/dongsoop/timetable/service/TimetableServiceImpl.java

기존에 각 시간표만 제거할 수 있던 API와 별개로,  
특정 학기를 제거했을 때 해당 학기의 모든 시간표를 제거하는 API를 추가하였습니다.

시간표 학기 기준 전체 삭제 기능 추가

---

src/main/java/com/dongsoop/dongsoop/timetable/controller/TimetableController.java
src/main/java/com/dongsoop/dongsoop/timetable/service/TimetableService.java
src/main/java/com/dongsoop/dongsoop/timetable/service/TimetableServiceImpl.java

시간표 이미지로 등록 기능과 같이 여러 시간표 정보를 한 번에 등록할 수 있는 API입니다.  
AI 사용률을 줄이기 위해 검증에 성공한 시간표만 저장되며, 검증에 실패한 시간표는 저장되지 않습니다.
에러 처리는 다음과 같습니다.
- 전체 저장 실패할 경우 409 - (Conflict)
- 일부만 성공일 경우 207 (Multi Status)
- 응답 바디에 실패한 요청 데이터가 반환됩니다.
- 전체 성공한 경우 201 (Created)

다중 시간표 등록 API

---

src/main/java/com/dongsoop/dongsoop/chat/notification/ChatNotificationImpl.java
src/main/java/com/dongsoop/dongsoop/memberdevice/repository/MemberDeviceRepository.java
src/main/java/com/dongsoop/dongsoop/memberdevice/service/MemberDeviceService.java
src/main/java/com/dongsoop/dongsoop/memberdevice/service/MemberDeviceServiceImpl.java
src/main/java/com/dongsoop/dongsoop/notification/dto/MulticastMessageWithTokens.java
src/main/java/com/dongsoop/dongsoop/notification/exception/ResponseSizeUnmatchedToTokenSizeException.java
src/main/java/com/dongsoop/dongsoop/notification/service/FCMService.java
src/main/java/com/dongsoop/dongsoop/notification/service/FCMServiceImpl.java
src/main/java/com/dongsoop/dongsoop/notification/service/NotificationService.java
src/main/java/com/dongsoop/dongsoop/notification/service/NotificationServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/apply/notification/RecruitmentApplyNotification.java

- 알림 전송 시 `UNREGISTERED`, `INVALID_ARGUMENT` 와 같이 토큰이 유효하지 않은 경우 토큰 제거
- 알림 로직 비동기 처리
- 요청 처리 시 알림 성공 여부과 관계없이 정상 응답처리

알림 전송 시 유효하지 않은 토큰 제거

---

src/main/java/com/dongsoop/dongsoop/notification/controller/NotificationController.java
src/main/java/com/dongsoop/dongsoop/notification/repository/NotificationRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/notification/repository/NotificationRepositoryCustomImpl.java
src/main/java/com/dongsoop/dongsoop/notification/service/NotificationService.java
src/main/java/com/dongsoop/dongsoop/notification/service/NotificationServiceImpl.java

-
- 기획 상 전체 읽음을 눌렀을 때 뱃지를 초기화해야 합니다.
3분

특정 회원의 전체 알림 읽음 처리 구현

---

src/main/java/com/dongsoop/dongsoop/home/controller/HomeController.java
src/main/java/com/dongsoop/dongsoop/home/service/HomeService.java
src/main/java/com/dongsoop/dongsoop/home/service/HomeServiceImpl.java
src/main/java/com/dongsoop/dongsoop/notice/repository/NoticeRepositoryCustom.java
src/main/java/com/dongsoop/dongsoop/notice/repository/NoticeRepositoryCustomImpl.java

-
- 비회원도 학사 정보를 조회할 수 있어야 합니다.
5분

비회원을 위한 홈 API 구현

---

src/main/java/com/dongsoop/dongsoop/notice/dto/HomeNotice.java
src/main/java/com/dongsoop/dongsoop/notice/repository/NoticeRepositoryCustomImpl.java

Closes #205 
- 공지 크롤링 시 학과에 따라 공지 타입을 변환하는 과정에서 문제가 발생하여 500 에러
- Expressions가 enum을 감쌌을 때, ORDINAL 또는 NAME중 어떤 값을 사용해야 할지 모르는 문제
3분

fix(home): move department to NoticeType method to dto

---

src/main/java/com/dongsoop/dongsoop/notification/service/NotificationSendServiceImpl.java

공지사항 모바일 알림 실패 해결

---

src/main/java/com/dongsoop/dongsoop/jwt/handler/JwtLogoutHandler.java

-
- 로그아웃 후에 알림 목록을 확인할 수 없지만, 알림 뱃지가 남아있는 문제
0분

로그아웃 시 사용자 모바일 알림 뱃지 초기화

---

src/main/java/com/dongsoop/dongsoop/chat/controller/ChatController.java
src/main/java/com/dongsoop/dongsoop/chat/dto/CreateChatRoomByAdminRequest.java

-
- 과팅 기능 중 서버에서 채팅방 생성 로직을 필요로 합니다.
3분

어드민에 의한 채팅방 생성

---

src/main/java/com/dongsoop/dongsoop/board/RecruitmentBoard.java
src/main/java/com/dongsoop/dongsoop/chat/exception/ManagerLeaveRestrictedException.java
src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
src/main/java/com/dongsoop/dongsoop/chat/util/ChatCommonUtils.java
src/main/java/com/dongsoop/dongsoop/chat/validator/ChatValidator.java
src/main/java/com/dongsoop/dongsoop/recruitment/board/project/service/ProjectBoardServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/board/study/service/StudyBoardServiceImpl.java
src/main/java/com/dongsoop/dongsoop/recruitment/board/tutoring/service/TutoringBoardServiceImpl.java

Closes #이슈번호
- 모집 게시글의 매니저가 모집 기간 중에 혼자 채팅방을 나가는 경우, 다른 사용자들이 지원했을 때 매니저가 없어서 소통이 불가능한 상황이 발생했습니다.
- **모집기간 중 + 혼자 있음** → 나가기 제한
- **모집기간 중 + 다른 사람 있음** → 나갈 수 있음
- **모집기간 종료 후** → 나갈 수 있음
- **일반 채팅방** → 제한 없음
- 모집기간 + 1일 후 TTL를 통한 만료 데이터 자동 삭제
10분

매니저 나가기 제한 기능 구현

---

src/main/java/com/dongsoop/dongsoop/search/repository/BoardSearchRepository.java

기존 시스템에서는 게시글 생성 시 자신의 학과 및 다른 학과를 대상으로 모집할 수 있도록 departmentTypeList 기능이 구현되어 있었습니다. 게시판 목록에서는 정상적으로 작동하여 선택된 다른 학과에서도 해당 게시글을 볼 수 있었습니다.
하지만 검색 기능에서는 학과 태그 목록이 누락되어 다음과 같은 문제가 발생함
- 컴퓨터소프트웨어공학과 학생이 게시글 작성
- departmentTypeList에 웹응용소프트웨어공학과, 인공지능소프트웨어학과 포함
- 게시판 목록: 웹응용소프트웨어공학과 학생들도 해당 글을 볼 수 있음
- 검색: 웹응용소프트웨어공학과로 검색하면 해당 글이 검색되지 않음
- 서버속 logstash에 departmentTypeList 등록
- 기존 게시판 목록 기능은 그대로 유지하면서 검색 기능의 일관성 확보
- PROJECT/STUDY/TUTORING 검색 성능 및 정확도 향상
- 한글-영어 혼합 키워드 검색 지원 강화
2분

교차 학과 모집 게시글 검색 지원 및 한글-영어 혼합 텍스트 검색 개선

---

src/main/java/com/dongsoop/dongsoop/chat/controller/ChatSocketController.java
src/main/java/com/dongsoop/dongsoop/chat/dto/ChatRoomUpdateDto.java
src/main/java/com/dongsoop/dongsoop/chat/entity/ChatNotificationType.java
src/main/java/com/dongsoop/dongsoop/chat/service/ChatRoomService.java
src/main/java/com/dongsoop/dongsoop/chat/service/ChatService.java
src/main/java/com/dongsoop/dongsoop/chat/session/WebSocketSessionManager.java
src/main/java/com/dongsoop/dongsoop/common/handler/websocket/StompHandler.java
src/main/java/com/dongsoop/dongsoop/marketplace/service/MarketplaceContactServiceImpl.java

#223 
- 기존 채팅방 목록은 새로운 메시지가 올 때마다 /chat/rooms API를 재호출해야 했음
- 사용자가 목록 화면에서 다른 채팅방의 새 메시지를 실시간으로 확인할 수 없었음
- HTTP 폴링 방식으로 인한 불필요한 네트워크 요청과 리소스 소모 발생
- 앱 사용성 개선을 위해 실시간 채팅방 목록 업데이트 기능이 필요했음
- 장터 게시글에서 "거래하기" 클릭시 기존 1:1 채팅방으로 연결되어 이전 대화내역과 섞임
- 장터 거래와 일반 개인 대화 구분 불가능
10분

장터채팅방 분리 및 채팅방 목록에 글로벌 WebSocket 알림 구현
